spring.data.mongodb.uri=mongodb+srv://user:user@live-newsfeed.kss1dwt.mongodb.net
# spring.data.mongodb.host=
# spring.data.mongodb.port=
spring.data.mongodb.database=live-newsfeed
spring.data.mongodb.username=user
spring.data.mongodb.password=user
spring.data.mongodb.auto-index-creation=true

